spring.application.name=backend
spring.datasource.url=jdbc:oracle:thin:@oracle.fil.univ-lille.fr:1521:filora
spring.datasource.username=RIGUET
spring.datasource.password=valeriana
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

ldap.host=ldap.eu.jumpcloud.com
ldap.port=389
ldap.org-id=69ade7aa293a7e69f85c1df7

taiga.url=https://api.taiga.io/api/v1
taiga.username=billal.azdad.etu@univ-lille.fr
taiga.password=ton_mot_de_pass_taiga

jwt.secret=VGhpc0lzQVNlY3JldEtleVRoYXRJc0V4YWN0bHlTaXh0eUZvdXJDaGFyYWN0ZXJzTG9uZ0ZvckhTNTEyQWxnbw==
jwt.expirationTime=8640000

mistral.api.key=3mfokyTBzXtNbni70rVEstVVBiVRZCEf
mistral.api.url=https://api.mistral.ai/v1/chat/completions
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
